version: "3.4"

services:
  microblog:
    build: .
    container_name: microblog
    volumes: 
      - .:/usr/src/app
    ports:
      - '5000:5000'
    networks:
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
